# 04 - Model Explainability and Business Impact

In [1]:

import sqlalchemy
import pandas as pd
import numpy as np
import mlflow
from shopsense.database import execute_query
from shopsense.features import compute_rfm_features, compute_behavioral_features, compute_transaction_features, build_master_feature_table
from shopsense.models.churn_model import evaluate_churn_model
from shopsense.evaluation import compute_shap_values, explain_single_prediction, compute_shap_dependence, estimate_churn_business_impact, detect_feature_drift, generate_model_report

engine = sqlalchemy.create_engine('postgresql://postgres:admin123@localhost:5432/postgres')

## Rebuild Master Feature Table

In [2]:

customers_df = execute_query("SELECT * FROM shopsense.customers", engine)
transactions_df = execute_query("SELECT * FROM shopsense.transactions", engine)
events_df = execute_query("SELECT * FROM shopsense.events", engine)

snapshot_date = "2023-12-31"
rfm = compute_rfm_features(transactions_df, snapshot_date)
beh = compute_behavioral_features(events_df, transactions_df, snapshot_date)
txn = compute_transaction_features(transactions_df, snapshot_date)
master_df = build_master_feature_table(customers_df, rfm, beh, txn)

## Load Best Registered Model

In [3]:

# Load staging model
try:
    model = mlflow.sklearn.load_model("models:/shopsense_churn_model/Staging")
    print("Model loaded from MLflow Model Registry Staging stage.")
except Exception as e:
    # Try alias
    try:
        model = mlflow.sklearn.load_model("models:/shopsense_churn_model@staging")
        print("Model loaded from MLflow Model Registry using staging alias.")
    except Exception:
        # Fallback to local runs or direct training for explainability
        print("Staging model not found in registry. Training a local XGBoost pipeline for explainability.")
        from sklearn.pipeline import Pipeline
        from shopsense.models.churn_model import build_churn_preprocessing_pipeline, train_churn_model
        numeric_features = [
            "age", "recency_days", "frequency", "monetary_total", "monetary_avg",
            "total_sessions", "avg_session_duration", "total_page_views",
            "cart_add_count", "cart_to_purchase_ratio", "wishlist_count",
            "days_since_last_event", "event_recency_trend", "category_diversity",
            "avg_discount_received", "return_rate", "revenue_last_30d",
            "revenue_last_90d", "revenue_last_180d", "purchase_gap_mean",
            "purchase_gap_std", "peak_season_purchase_ratio"
        ]
        categorical_features = ["gender", "city", "acquisition_channel", "preferred_device", "preferred_category", "preferred_payment", "rfm_segment"]
        preprocessor = build_churn_preprocessing_pipeline(numeric_features, categorical_features)
        X = master_df[numeric_features + categorical_features]
        y = master_df["churn_label"]
        model = train_churn_model(X, y, preprocessor, model_type="xgboost", random_state=42)

2026/06/05 17:14:33 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.schemas

2026/06/05 17:14:33 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.tables

2026/06/05 17:14:33 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.types

2026/06/05 17:14:33 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.constraints

2026/06/05 17:14:33 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.defaults

2026/06/05 17:14:33 INFO alembic.runtime.plugins: setup plugin alembic.autogenerate.comments

2026/06/05 17:14:34 INFO mlflow.store.db.utils: Creating initial MLflow database tables...

2026/06/05 17:14:34 INFO mlflow.store.db.utils: Updating database tables

2026/06/05 17:14:34 INFO alembic.runtime.migration: Context impl SQLiteImpl.

2026/06/05 17:14:34 INFO alembic.runtime.migration: Will assume non-transactional DDL.

2026/06/05 17:14:34 INFO alembic.runtime.migration: Context impl SQLiteImpl.

2026/06/05 17:14:34 INFO alembic.runtime.migration: Will assume non-transactional DDL.

2026/06/05 17:14:34 INFO mlflow.store.db.utils: Creating initial MLflow database tables...

2026/06/05 17:14:34 INFO mlflow.store.db.utils: Updating database tables

2026/06/05 17:14:34 INFO alembic.runtime.migration: Context impl SQLiteImpl.

2026/06/05 17:14:34 INFO alembic.runtime.migration: Will assume non-transactional DDL.

Model loaded from MLflow Model Registry Staging stage.

## Compute SHAP Explanations

In [4]:

# Extract preprocessor and transform features
preprocessor = model.steps[0][1]
numeric_features = [
    "age", "recency_days", "frequency", "monetary_total", "monetary_avg",
    "total_sessions", "avg_session_duration", "total_page_views",
    "cart_add_count", "cart_to_purchase_ratio", "wishlist_count",
    "days_since_last_event", "event_recency_trend", "category_diversity",
    "avg_discount_received", "return_rate", "revenue_last_30d",
    "revenue_last_90d", "revenue_last_180d", "purchase_gap_mean",
    "purchase_gap_std", "peak_season_purchase_ratio"
]
categorical_features = ["gender", "city", "acquisition_channel", "preferred_device", "preferred_category", "preferred_payment", "rfm_segment"]
X = master_df[numeric_features + categorical_features]

X_prep = pd.DataFrame(preprocessor.transform(X), columns=preprocessor.get_feature_names_out())

shap_results = compute_shap_values(model, X_prep, model_type="xgboost")
print("SHAP expected value:", shap_results["expected_value"])
print("\nTop 5 contributing features (mean absolute SHAP):")
print(shap_results["mean_abs_shap"].head())

SHAP expected value: 0.003998829051852226

Top 5 contributing features (mean absolute SHAP):
num__frequency         6.441009
num__age               0.000000
num__recency_days      0.000000
num__monetary_total    0.000000
num__monetary_avg      0.000000
dtype: float32

## Single Prediction Local Explanation

In [5]:

local_exp = explain_single_prediction(
    shap_results["shap_values"],
    shap_results["feature_names"],
    shap_results["expected_value"],
    instance_index=0,
    top_n=5,
    X_sample=X_prep
)
print("Local explanation for customer at index 0:")
local_exp

Local explanation for customer at index 0:

               feature  shap_value  feature_value
0       num__frequency   -6.442081       1.413045
1             num__age    0.000000       2.361690
2    num__recency_days    0.000000      -0.540855
3  num__monetary_total    0.000000       1.075595
4    num__monetary_avg    0.000000       0.019629

## Business Impact Estimation

In [6]:

business_impact = estimate_churn_business_impact(customers_df, transactions_df, model, X, threshold=0.5)
print(f"Predicted Churners: {business_impact['predicted_churners_count']}")
print(f"Total Revenue At Risk: ₹{business_impact['total_revenue_at_risk']:,.2f}")
print(f"Potential Revenue Saved (30% retention): ₹{business_impact['potential_save_revenue_30pct']:,.2f}")
print(f"Potential Revenue Saved (50% retention): ₹{business_impact['potential_save_revenue_50pct']:,.2f}")
print("\nTop 5 highest risk customers (by revenue):")
print(business_impact["top_10_revenue_at_risk_customers"][:5])

Predicted Churners: 229
Total Revenue At Risk: ₹477,586.37
Potential Revenue Saved (30% retention): ₹143,275.91
Potential Revenue Saved (50% retention): ₹238,793.18

Top 5 highest risk customers (by revenue):
['CUST_000384', 'CUST_000744', 'CUST_000584', 'CUST_000569', 'CUST_000635']

## Feature Drift Detection

In [7]:

# Split master table into reference (past) and current (simulating new data)
ref_df = master_df.iloc[:500]
cur_df = master_df.iloc[500:]

drift_report = detect_feature_drift(ref_df, cur_df, numeric_features, categorical_features)
print("Feature Drift Analysis (p-value < 0.05 indicates drift):")
drift_report

Feature Drift Analysis (p-value < 0.05 indicates drift):

,feature,feature_type,test_name,statistic,p_value,drift_detected
0,monetary_avg,numeric,Kolmogorov-Smirnov,0.114000,0.002990,True
1,cart_add_count,numeric,Kolmogorov-Smirnov,0.092000,0.028996,True
2,wishlist_count,numeric,Kolmogorov-Smirnov,0.082000,0.069301,False
3,age,numeric,Kolmogorov-Smirnov,0.082000,0.069301,False
4,return_rate,numeric,Kolmogorov-Smirnov,0.082000,0.069301,False
5,city,categorical,Chi-Square,27.437880,0.094860,False
6,event_recency_trend,numeric,Kolmogorov-Smirnov,0.078000,0.095465,False
7,gender,categorical,Chi-Square,4.392323,0.111229,False
8,total_page_views,numeric,Kolmogorov-Smirnov,0.076000,0.111368,False
9,total_sessions,numeric,Kolmogorov-Smirnov,0.064000,0.257607,False
10,cart_to_purchase_ratio,numeric,Kolmogorov-Smirnov,0.064000,0.257607,False
11,purchase_gap_mean,numeric,Kolmogorov-Smirnov,0.062000,0.291925,False
12,monetary_total,numeric,Kolmogorov-Smirnov,0.060000,0.329358,False
13,preferred_category,categorical,Chi-Square,5.556606,0.351779,False
14,avg_discount_received,numeric,Kolmogorov-Smirnov,0.054000,0.459923,False
15,purchase_gap_std,numeric,Kolmogorov-Smirnov,0.052000,0.508917,False
16,avg_session_duration,numeric,Kolmogorov-Smirnov,0.046000,0.665922,False
17,days_since_last_event,numeric,Kolmogorov-Smirnov,0.046000,0.665922,False
18,category_diversity,numeric,Kolmogorov-Smirnov,0.044000,0.718919,False
19,acquisition_channel,categorical,Chi-Square,2.046009,0.727297,False
20,revenue_last_90d,numeric,Kolmogorov-Smirnov,0.042000,0.770437,False
21,peak_season_purchase_ratio,numeric,Kolmogorov-Smirnov,0.040000,0.819151,False
22,rfm_segment,categorical,Chi-Square,1.444208,0.836476,False
23,preferred_payment,categorical,Chi-Square,1.151879,0.885956,False
24,revenue_last_180d,numeric,Kolmogorov-Smirnov,0.036000,0.902691,False
25,frequency,numeric,Kolmogorov-Smirnov,0.036000,0.902691,False
26,recency_days,numeric,Kolmogorov-Smirnov,0.034000,0.935112,False
27,revenue_last_30d,numeric,Kolmogorov-Smirnov,0.034000,0.935112,False
28,preferred_device,categorical,Chi-Square,0.000000,1.000000,False

## Generate Automated Model Report

In [8]:

# Re-evaluate models to pass to report
from shopsense.models.churn_model import evaluate_churn_model
from shopsense.models.revenue_model import evaluate_forecast
from shopsense.models.segmentation_model import prepare_clustering_features, train_segmentation_model, profile_clusters

y_test = master_df["churn_label"]
churn_eval = evaluate_churn_model(model, X, y_test, threshold=0.5)

# Forecast metrics
tx = transactions_df.copy()
tx["transaction_date"] = pd.to_datetime(tx["transaction_date"])
tx["net_revenue"] = tx["quantity"] * tx["unit_price"] * (1.0 - tx["discount_pct"])
tx.loc[tx["return_flag"] == 1, "net_revenue"] = 0.0
ts = tx.set_index("transaction_date")["net_revenue"].resample("M").sum()
from shopsense.models.revenue_model import train_sarima_model
res_ts, fitted_ts = train_sarima_model(ts, order=(1, 1, 1), seasonal_order=(1, 0, 0, 12))
forecast_eval = evaluate_forecast(ts, fitted_ts)

# Clustering profiling
X_cl_scaled, cl_features, _ = prepare_clustering_features(master_df)
kmeans, labels = train_segmentation_model(X_cl_scaled, n_clusters=3, random_state=42)
cluster_profile = profile_clusters(master_df, labels, cl_features)

report_path = generate_model_report(churn_eval, forecast_eval, cluster_profile, shap_results)
print(f"Generated automated report successfully at: {report_path}")

C:\Users\harsha vashi\AppData\Local\Temp\ipykernel_20732\1498567616.py:14: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  ts = tx.set_index("transaction_date")["net_revenue"].resample("M").sum()

Generated automated report successfully at: reports/model_report.md